IntegerSortWebApp/Models/Sort.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace IntegerSortWebApp.Models
{
    public class Sort
    {
        [Key]
        [JsonIgnore]
        public int Id { get; set; }
        [Required]
        public long SortTime { get; set; }
        [Required]
        public int SortDirection { get; set; }

        public virtual IEnumerable<Number> Numbers { get; set; }
    }
}

IntegerSortWebApp/Controllers/JSONHandlingController.cs
using IntegerSortWebApp.App_Data;
using IntegerSortWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace IntegerSortWebApp.Controllers
{
    public class JSONHandlingController : Controller
    {

        private readonly IntegerSortDBContext _database;

        public JSONHandlingController(IntegerSortDBContext database)
        {
            _database = database;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ImportJSON()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ImportJSONAsync(IFormFile fileToUpload)
        {
            try
            {
                if (!fileToUpload.FileName.EndsWith(".json"))
                {
                    return View();
                }

                var filePath = fileToUpload.FileName;
                fileToUpload.OpenReadStream();

                string fileContent = null;

                using (var stream = new StreamReader(fileToUpload.OpenReadStream(), true))
                {
                    fileContent = stream.ReadToEnd();

                    List<Sort> test = JsonSerializer.Deserialize<List<Sort>>(fileContent);

                    _database.AddRange(test);
                    _database.SaveChanges();
                }

                return View();
            }
            catch (Exception ex)
            {
                return View();
            }

        }

        public IActionResult ExportJSON()
        {
            try
            {
                if (_database.Numbers.ToList().Count > 0)
                    return Json(_database.Sorts.ToList(), new JsonSerializerOptions { WriteIndented = true });
                else
                    return View();
            }
            catch (Exception ex)
            {
                return View();
            }
        }
    }
}

IntegerSortWebApp/Controllers/SortsController.cs
using IntegerSortWebApp.App_Data;
using IntegerSortWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace IntegerSortWebApp.Controllers
{
    public class SortsController : Controller
    {
        private readonly IntegerSortDBContext _database;

        public SortsController(IntegerSortDBContext database)
        {
            _database = database;
        }

        public IActionResult Index(int SortID)
        {
            IEnumerable<Sort> sortList = _database.Sorts;
            return View(sortList);
        }

        public IActionResult CreateSort()
        {
            return RedirectToAction("Index", "Sorts");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateSort(IFormCollection formCollection)
        {
            Sort newSort = new Sort();
            string integer = formCollection["Integer"];
            int sortOrder;
            if (!Int32.TryParse(formCollection["SortOrder"], out sortOrder))
                return RedirectToAction("Index", "Sorts");
            newSort.SortDirection = sortOrder;
            String[] numberStringArray = integer.Split(",");
            List<Number> numbers = new List<Number>();

            for (int i = 0; i < numberStringArray.Length; i++)
            {
                int newNumber;
                if (!Int32.TryParse(numberStringArray[i], out newNumber))
                    return RedirectToAction("Index", "Sorts");
                numbers.Add(new Number { Integer = newNumber });
            }

            try
            {
                var watch = new System.Diagnostics.Stopwatch();
                // Start performance metric
                watch.Start();
                if (sortOrder == (int)SortOrder.Ascending)
                    _database.Numbers.AddRange(numbers.OrderBy(num => num.Integer));
                else
                    _database.Numbers.AddRange(numbers.OrderByDescending(num => num.Integer));
                watch.Stop();
                newSort.SortTime = watch.ElapsedMilliseconds;
                newSort.Numbers = numbers;
                _database.Sorts.Add(newSort);
                _database.SaveChanges();
                TempData["Success"] = "Successfully added new integers to database";
                return RedirectToAction("Index", "Sorts");
            }
            catch (Exception ex)
            {
                TempData["Error"] = "There was an error adding new integers to database";
                return RedirectToAction("Index");
            }
        }

        public IActionResult RemoveSort(int? Id)
        {
            Sort? sortRecord = _database.Sorts.Find(Id);
            if (sortRecord == null)
                return View();

            try
            {
                _database.Remove(sortRecord);
                _database.SaveChanges();
                TempData["Success"] = "Successfully removed sort from database";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["Error"] = "There was an error removing sort from database";
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

IntegerSortWebApp/Views/Sorts/Index.cshtml
@model IEnumerable<Sort>

@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="container">
        <div class="row">
            <div class="col-sm"><a asp-controller="Number" asp-action="AddNumbers" class="btn btn-outline-primary">New Sort</a></div>
            <div class="col-sm"><a asp-controller="JSONHandling" asp-action="ImportJSON" class="btn btn-outline-primary">Import JSON</a></div>

            @if (Model.Count() > 0)
            {
                <div class="col-sm"><a asp-controller="JSONHandling" asp-action="ExportJSON" class="btn btn-outline-primary">Export JSON</a></div>
            }
        </div>
    </div>
</div>

@if (ViewData["Error"] != null)
{
    <div class="red">
        <p><strong>@ViewData["Error"].ToString()</strong></p>
    </div>
}
@if (TempData["Success"] != null)
{
    <div class="green">
        <p><strong>@TempData["Success"].ToString()</strong></p>
    </div>
}

<h2 class="text-primary">Sorts Table</h2>

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Sort ID
            </th>
            <th>
                Sort Time (ms)
            </th>
            <th>
                Sort Direction
            </th>
            <th>

            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td width="50%">
                    <a asp-route-id=@obj.Id asp-controller="Number" asp-action="Index">@obj.Id</a>
                </td>

                <td width="30%">

                    @obj.SortTime
                </td>
                <td>
                    @if (@obj.SortDirection == 0)
                    {
                        <div>Ascending</div>
                    }
                    else
                    {
                        <div>Descending</div>

                    }
                </td>
                <td>
                    <div><a asp-route-id=@obj.Id value="Remove" asp-controller="Sorts" asp-action="RemoveSort" class="btn btn-outline-primary">Remove</a></div>
                </td>
            </tr>
        }
    </tbody>
</table>

IntegerSortWebApp/Views/Sorts/RemoveSort.cshtml
<h2>Record not found</h2>
<a asp-controller="Sorts" asp-action="Index" class="btn btn-outline-primary">Back</a>